project:
  type: website
  output-dir: docs
search: false
sidebar: false
website:
  search: false
  sidebar: false
  navbar:
    
    background: "#333"
    foreground: white
    search: false
    pinned: false
    collapse: false
    left:
      - text: "Home"
        href: index.qmd
      - text: "Projects"
        href: projects.qmd

format:
  html:
    theme: 
      - yeti
      - projects.scss
    backgroundcolor: whitesmoke
    toc: true
    smooth-scroll: true



