project:
  type: website
  output-dir: docs

website:
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Projects"
        href: projects.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true



