project:
  type: website
  output-dir: docs
search: false
sidebar: false
website:
  search: false
  sidebar: false
  navbar:
    background: grey
    foreground: white
    search: true
    left:
      - text: "Home"
        href: shivasinghbagri.qmd
      - text: "Projects"
        href: projects.qmd

format:
  html:
    theme: 
      - yeti
      - projects.scss
    backgroundcolor: whitesmoke
    toc: true
    smooth-scroll: true



