project:
  type: website
  output-dir: docs
search: false
sidebar: false
website:
  search: false
  sidebar: false


format:
  html:
    theme: 
      - yeti
      - projects.scss
    backgroundcolor: whitesmoke
    toc: true
    smooth-scroll: true



